export const CONFIRM_LOGIN = 'CONFIRM_LOGIN';
export const GET_CURRENCIES_LIST = 'GET_CURRENCIES_LIST';
export const ADD_EXPENSE = 'ADD_EXPENSE';
export const UPDATE_EXPENSES_LIST = 'UPDATE_EXPENSES_LIST';
export const TOGGLE_EDIT_MODE = 'TOGGLE_EDIT_MODE';
